#!/usr/bin/python
import os
import json

apps = ("video", )

fixture_file = "initial_data.json"

for app in apps:
    os.system(
        "./manage.py dumpdata --indent=2 %s > %s/fixtures/%s" % (app, app,
                                                                 fixture_file)
    )

os.system("./manage.py dumpdata --indent=2 auth > temp.json")

auth_fixtures_raw = json.loads(open("temp.json", "r").read())
auth_fixtures = []
remove = ["auth.permission"]
for fixture in auth_fixtures_raw:
    if fixture["model"] not in remove:
        auth_fixtures.append(fixture)

fixture_file = open("initial_data.json", "w")
fixture_file.write(json.dumps(auth_fixtures, sort_keys=True, indent=2))
fixture_file.close()

os.remove("temp.json")
