# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_quota', models.IntegerField(default=52428800)),
                ('video_quota', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('page_url', models.CharField(max_length=256)),
                ('duration', models.IntegerField(default=0)),
                ('filename', models.CharField(max_length=256)),
                ('extension', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=24)),
                ('thumbnail', models.FileField(null=True, upload_to=b'thumbnails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
